export const SIGNUPSTARTED = "SIGNUPSTARTED";
export const SIGNUPSUCCESS = "SIGNUPSUCCESS";
export const SIGNUPFAILURE = "SIGNUPFAILURE";
export const CLEARLASTERROR = "CLEARLASTERROR";
export const SIGNINSTARTED = "SIGNINSTARTED";
export const SIGNINSUCCESS = "SIGNINSUCCESS";
export const SIGNINFAILURE = "SIGNINFAILURE";
export const LOGOUT = "LOGOUT";
